Improve stability
BoscoDomingo/SpotifyMatcher pull request #4
Opened 2021-03-26 17:27 UTC by jakelauer

This PR fixes a couple of issues I ran into while using this tool.

- Enables partial uploads so that you can determine if there is a problem early, rather than waiting for the entire scan to finish
- Fixes a place that was failing to pass the playlist_id
- Other minor fixes

2021-03-29 08:42 UTC, BoscoDomingo commented
Thank you so very much for this!! We love that our small app helped you and I'll take a look at your code and make sure everything works as intended as soon as I get some time this week. I ought to set up GitHub Actions or something, might get around to that one day , but for now manual review it is ;)

2021-04-01 14:48 UTC, BoscoDomingo requested changes
So the following error appeared at the very end. Should be a relatively easy fix (variable not declared)
![image](https://user-images.githubusercontent.com/46006784/113311837-fe937f00-9309-11eb-9c55-45f6da561151.png)

2021-04-01 15:07 UTC, BoscoDomingo requested changes
I'll be leaving a PR in your fork with some changes, although there are still some tweaks I'd like you to do regardless to approve this one and merge it. Thanks again for your time and contribution :)

2021-04-01 15:07 UTC, BoscoDomingo commented on main.py
> +        playlist_file.close()
Could you move this to a function? Something like `cache_playlist_id()` or similar

2021-04-01 15:07 UTC, BoscoDomingo commented on main.py
> +        append_write = 'wb+'
Same here, make it a function like `decide_append_write_mode()`

2021-04-01 15:23 UTC, BoscoDomingo commented
![image](https://user-images.githubusercontent.com/46006784/113316494-b2970900-930e-11eb-9547-9ed09195e627.png)
This is with my changes in the aforementioned `PRs/#4` where you can see I had some songs already cached + some new ones, and the numbers are weird, so I definitely didn't fix it 100%.

2021-04-01 16:25 UTC, jakelauer commented
I'll take a look at this when I get a chance!

2021-04-01 16:25 UTC, jakelauer commented
PS, thank you for writing this, it's literally the only thing on the internet I could find that would let me move my music to Spotify the way I wanted.

2021-04-01 16:27 UTC, jakelauer commented
PPS I am a JavaScript dev by trade and literally have never written a line of python in my life before this PR, so keep that in mind! I'm probably not the best person to make something pretty and nice. But I can give it a whack.

2021-04-01 21:24 UTC, BoscoDomingo commented
> 
> 
> PS, thank you for writing this, it's literally the only thing on the internet I could find that would let me move my music to Spotify the way I wanted.

Aboslutely, I'm glad it could help someone else other than me, it's the main reason why I put it out there!!

Also I'm quite impressed you jumped onto a different language like that, massive props to you for figuring it out and making it work. I totally understand it not being the absolute most pristine thing if it's your first ever go at Python lol. Most people (including me in this specific case) don't even get it right after becoming "experts" 🤣 Don't fret about it. The fact you contributed is already way above and beyond what most people even bother doing

2024-04-17 19:29 UTC, closed without merging